"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Afj5IJytny4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Separator } from "@/components/ui/separator"
import { ReactNode } from "react"
import { getClientInfo, getClientIP, ipinfoOutput } from "@/lib/ipinfo";

function Spoiler({children}: {children: ReactNode}) {
	return (
		<span className="bg-muted-foreground text-muted-foreground hover:text-muted-foreground hover:bg-transparent pointer-events-auto z-[20]">{children}</span>
	)
}

export async function Biocard() {

  const ip: string = await getClientIP()
  const d: ipinfoOutput = await getClientInfo(ip)

  const fun: [string,string][] = [
    ["IP",ip],
    ["ISP",d.isp],
    ["ASN",d.as],
    ["City",d.city],
    ["Country",d.country]
  ]

  const funnier: ReactNode[] = []

  fun.map((y,index)=>{
    funnier.push(
      <div key={index.toString()} className="flex items-center justify-between text-muted-foreground">
        <div>{y[0]}</div>
        <div>{y[1]}</div>
      </div>
    )
  })

  return (
    <Card className="w-[600px] max-w-md mx-auto text-left">
      <CardHeader className="bg-primary rounded-xl text-primary-foreground p-6">
        <div className="flex items-center gap-4">
          <Avatar className="border-primary">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>?</AvatarFallback>
          </Avatar>
          <div className="grid gap-1">
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-bold">OCbwoy3</h2>
            </div>
            <div className="flex items-center gap-2 text-sm text-primary-foreground/80">
              <Link href="https://x.com/ocbwoy3" className="flex items-center gap-2" prefetch={false}>
                Twitter
              </Link>
              <Link href="https://discord.com/users/486147449703104523" className="flex items-center gap-2" prefetch={false}>
                Discord
              </Link>
            </div>
          </div>
        </div>
      </CardHeader>
      <CardContent className="p-6 grid gap-4">
        <div className="grid gap-2">
          <h3 className="text-lg font-semibold">About Me</h3>
          <p className="text-muted-foreground">
            I made a Roblox Remote Admin.<br/>
            <Spoiler>and yes, i am a gay furry</Spoiler>
          </p>
        </div>
        <Separator />
        <h3 className="text-lg font-semibold">Your Information</h3>
        {funnier}
      </CardContent>
    </Card>
  )
}
